spring:
  application:
    name: spotify-gateway
  cloud:
    gateway:
      routes:
        - id: SpotifyuserService
          uri: http://localhost:8010
          predicates:
            - Path=/api/v1/user/**

        - id: authService
          uri: http://localhost:8040
          predicates:
            - Path=/api/v1/auth/**

#      Music service routing
        - id: SpotifyMusicService
          uri: http://localhost:8020
          predicates:
            - Path=/api/v1/music/**

        - id: SpotifyListService
          uri: http://localhost:8030
          predicates:
            - Path=/api/v1/list/**
          filters:
            - AuthenticationFilter

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
server:
  port: 8050
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/